### PR TITLE
#1 Fix Animation Controller not disposing

### PR DESCRIPTION
**Pull request by UsamaKarim**
Using .map() actually converts a list into an iterator, and an iterator in dart is lazy-loaded. Either converting it into a list or using forEach/for-loop makes it work.

### CODE REVIEW

**Comment by UsamaKarim** [comment]
fix for #1

**Review by deep-mindinventory — COMMENTED** [review]
It is not best practice to do changes to the .lock file. It is generated according to .yaml file. it can be deleted and created new too.

**Comment by UsamaKarim** [comment]
By default `pubspec.lock` file is not added to `gitignore` while generating a new flutter project/package. So, it's pushed as it is.

**Review by deep-mindinventory — CHANGES_REQUESTED** [review]
Yes, @UsamaKarim Please keep it as it is.

**Pull request merged**
